// <auto-generated />
using IsBasvurusu.Models.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IsBasvurusu.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    partial class UygulamaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IsBasvurusu.Models.entity.Kisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Kisiler");
                });

            modelBuilder.Entity("IsBasvurusu.Models.entity.Sehir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Sehirler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Adana"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ankara"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "İstanbul"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "İzmir"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Gaziantep"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Mersin"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Muğla"
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Antalya"
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Elazığ"
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Trabzon"
                        },
                        new
                        {
                            Id = 11,
                            Ad = "Rize"
                        },
                        new
                        {
                            Id = 12,
                            Ad = "Eskişehir"
                        },
                        new
                        {
                            Id = 13,
                            Ad = "Afyon"
                        },
                        new
                        {
                            Id = 14,
                            Ad = "Çanakkale"
                        },
                        new
                        {
                            Id = 15,
                            Ad = "Krakow"
                        },
                        new
                        {
                            Id = 16,
                            Ad = "Barcelona"
                        },
                        new
                        {
                            Id = 17,
                            Ad = "Hamburg"
                        },
                        new
                        {
                            Id = 18,
                            Ad = "Budapeşte"
                        },
                        new
                        {
                            Id = 19,
                            Ad = "Kahire"
                        },
                        new
                        {
                            Id = 20,
                            Ad = "Rio"
                        });
                });

            modelBuilder.Entity("KisiSehir", b =>
                {
                    b.Property<int>("KisilerId")
                        .HasColumnType("int");

                    b.Property<int>("SehirlerId")
                        .HasColumnType("int");

                    b.HasKey("KisilerId", "SehirlerId");

                    b.HasIndex("SehirlerId");

                    b.ToTable("KisiSehir");
                });

            modelBuilder.Entity("KisiSehir", b =>
                {
                    b.HasOne("IsBasvurusu.Models.entity.Kisi", null)
                        .WithMany()
                        .HasForeignKey("KisilerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IsBasvurusu.Models.entity.Sehir", null)
                        .WithMany()
                        .HasForeignKey("SehirlerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
